# Адрес Minter
address_account = "Mx..."
# Приватный ключ аккаунта 
privatkey = "privatkey"
# Список получателей с суммами и монетами
list_address = [["Mx1...", "100", "COINNAME1"], ["Mx2..", "50", "COINNAME2"]]
# Nonce берем из https://explorer.minter.network/
nonce = 94
# Монета для оплаты комиссии
gas_coin = "BIP"



